# This file stores configurations for your Shopify app.

scopes = "write_products,read_orders,write_orders,read_script_tags,write_script_tags,read_draft_orders,write_draft_orders,read_customers,write_customers"