export const sectionData = [
  // {
  //   section_id: 1,
  //   section_name: "Order confirmed",
  //   status: 1,
  //   html: '<div className="section mt-5" id="1"><div className="section__header os-header"><div className="px-2"><Icon source={QuestionMarkMajor} color="base" /></div><svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#000" strokeWidth="2" className="os-header__hanging-icon checkmark"><path className="checkmark__circle" d="M25 49c13.255 0 24-10.745 24-24S38.255 1 25 1 1 11.745 1 25s10.745 24 24 24z"></path><path className="checkmark__check" d="M15 24.51l7.307 7.308L35.125 19"></path></svg><div className="d-flex flex-column px-3"><span>Order #1001</span><h2 className="header_title pt-1">Thank you (first name!)</h2></div></div></div>',
  //   type: "left-area",
  // },
  // {
  //   section_id: 2,
  //   section_name: "Customer information",
  //   status: 1,
  //   html: '<div className="section mt-3 pl-15" id="2"><div className="content-box order_confirmation"><div className="content-box-row pb-3"><div className="map"><img src="https://cdn.stilyoapps.com/v1/assets/img/map.png" style={{ width: "100%" }}/></div><div className="mx-3"><h2 className="mt-4 oc_title">Your order is confirmed</h2><SkeletonBodyText /></div><div className="mx-3"><hr /></div><div className="tracking-info mx-3"><div className="tracking-info-number" style={{ float: "left" }}  ><strong>Tracking number</strong><p><a style={{ color: "#15669d" }} href="#">XXXXXXXXXXXXX  </a></p></div><div style={{ float: "right" }}><Button primary>Track</Button></div></div></div></div></div>"',
  //   type: "left-area",
  // },
  {
    section_id: 3,
    section_name: "Donate for Ukraine",
    title: `<p style=\"text-align:center;\"><img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/></p>\n<p style=\"text-align:center;\"><span style=\"font-size: 24px;\"><strong>Stand with Ukraine</strong></span></p>\n<p style=\"text-align:center;\"><img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/> <img src=\"\thttps://cdn.shopify.com/s/files/1/0566/8523/2308/t/139/assets/1646372002.png?v=1646372003\" alt=\"undefined\" style=\"height: undefined;width: undefined\"/></p>\n`,
    display_donation_btn: true,
    btn_text: "Donate to support Ukraine",
    bg_color: "#e7d33b",
    color: "#000",
    status: 1,
    iconName: `<i className="fa fa-flag" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 4,
    section_name: "Birthday collector widget",
    title:
      '<p style="text-align:center;"><span style="font-size: 16px;"><strong>Let us know your birthday. a special gift will be heading your way!</strong></span></p>\n',
    date_format: [
      {
        value: "MM/DD/YYYY",
        label: "01/15/2023",
      },
      {
        value: "DD/MM/YYYY",
        label: "15/01/2023",
      },
      {
        value: "YYYY/MM/DD",
        label: "2023/01/15",
      },
      {
        value: "MM-DD-YYYY",
        label: "01-15-2023",
      },
      {
        value: "DD-MM-YYYY",
        label: "15-01-2023",
      },
      {
        value: "YYYY-MM-DD",
        label: "2023-01-15",
      },
      {
        value: "MMM DD YYYY",
        label: "Jan 15 2023",
      },
      {
        value: "DD MMM YYYY",
        label: "15 Jan 2023",
      },
      {
        value: "YYYY DD MMM",
        label: "2023 15 Jan",
      },
    ],
    placeholder_text: "Select your birthday",
    btn_text: "Submit",
    bg_color: "#197bbd",
    color: "#fff",
    thank_you_msg_txt: "Thank You!",
    thank_you_msg_txt_color: "#000",
    error_msg: "Birthday is required",
    error_msg_color: "#e32c2b",
    status: 1,
    iconName: `<i className="fa fa-calendar" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 5,
    section_name: "Call to action",
    title:
      "<p>In the text editor you have multiple options:<br>Bold, Underline, Italic and Strikethrough the text.<br>Change the format and size<br>Change the text’s color and background<br>Change the font​​​​​<br>Use a link<br>Change the alignment<br>Insert a horizontal line</p>\n",
    layout: [
      {
        value: "horizontal",
        label: "Horizontal",
      },
      {
        value: "vertical",
        label: "Vertical",
      },
    ],
    btn_text: "Action",
    bg_color: "#197bbd",
    color: "#fff",
    redirect_url: "https://crawlapps-trainee.myshopify.com",
    status: 1,
    selected_layout: "",
    iconName: `<i className=\"fa fa-phone\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 6,
    section_name: "Collection list",
    heading: "Collection list",
    head_color: "#000",
    head_fs_size: "18px",
    head_style: ["bold", "italic"],
    head_selected_text_transform: "",
    coll_title_color: "#000",
    coll_fs_size: "14px",
    coll_style: ["bold", "italic"],
    coll_selected_text_transform: "",
    coll_per_row: 2,
    content: [],
    status: 1,
    iconName: `<i className=\"fa fa-list-alt\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 7,
    section_name: "Custom HTML",
    custom_html:
      "<strong>Use HTML to format your text so it can be easily read.</strong>This text can be used to share information about your store.",
    status: 1,
    iconName: `<i className=\"fa fa-code\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 8,
    section_name: "Discount",
    title:
      '<p style="text-align:center;"><span style="font-size: 30px;">10% OFF DISCOUNT!</span></p>\n<p style="text-align:center;"><span style="font-size: 16px;">To thank you for your order, here is a 10% OFF coupon code for your next order.</span></p>\n',
    bg_color: "#000",
    btn_text: "Shop Now",
    btn_bg_color: "#197bbd",
    btn_color: "#fff",
    redirect_url: "https://crawlapps-trainee.myshopify.com",
    discount_code: "TAKE10OFF",
    discount_bg_color: "#fff",
    discount_color: "#000",
    term_condition_txt:
      '<p style="text-align:center;">Add terms &amp; conditions here, if needed</p>\n',
    status: 1,
    iconName: `<i className=\"fa fa-tag fa-lg\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 9,
    section_name: "Free text",
    title:
      "<p>In the text editor you have multiple options:<br>Bold, Underline, Italic and Strikethrough the text.<br>Change the format and size<br>Change the text’s color and background<br>Change the font​​​​​<br>Use a link<br>Change the alignment<br>Insert a horizontal line</p>\n",
    status: 1,
    iconName: `<i className=\"ri-file-list-line\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 10,
    section_name: "Image with text",
    img: "",
    title:
      "In the text editor you have multiple options:Bold, Underline, Italic and Strikethrough the text.Change the format and size Change the text’s color and background Change the font Use a link Change the alignment Insert a horizontal line",
    selected_img_align: "left",
    selected_img_layout: "square",
    redirect_url: "",
    status: 1,
    iconName: `<i className=\"fa fa-picture-o\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 11,
    section_name: "Link list",
    color: "#000",
    head_fs_size: "14",
    head_style: [],
    head_selected_text_transform: "",
    links: [{ name: "home", url: "#" }],
    status: 1,
    iconName: `<i className=\"fa fa-external-link\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 12,
    section_name: "Post purchase surveys",
    select_survey: "",
    show_survey_multiple_time: false,
    btn_text: "Submit",
    bg_color: "#197bbd",
    color: "#fff",
    next_btn_text: "Next",
    next_btn_bg_color: "#197bbd",
    next_btn_color: "#fff",
    prev_btn_text: "Previous",
    prev_btn_bg_color: "#197bbd",
    prev_btn_color: "#fff",
    thank_you_msg: "Thanks for filling out our survey!",
    thank_you_msg_color: "#000",
    error_msg: "Please answer the question",
    err_msg_color: "#e32c2b",
    place_holder_answer: "Enter answer",
    place_holder_dropdown: "Select",
    questions: [
      {
        question: "",
        answer_type: "",
        options: [""],
      },
    ],
    status: 1,
    iconName: `<i className=\"fa fa-file-text-o\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 13,
    section_name: "Product recommendations",
    settings: {
      title: {
        offer_name: "Offer name",
        widget_title:
          '<p style="text-align:center;"><span style="font-size: 16px;">We thought you may also like these items:</span></p>\n',
        selected_disp_widget: "above_widget",
        widget_title_bg_color: "transparent",
      },
      product_options: {
        products_display: "Shopify recommendations",
        exclusion_tag: false,
        exclusion_tags: [],
        hide_product: false,
        loader_text:
          '<p style="text-align:center;">We are looking for the best offers for you...</p>\n',
        title: "",
        products_per_row: 3,
        no_of_product: 12,
        arrow_color: "#000",
        display_qty_picker: true,
        qty_picker_txt: "Quantity",
        enable_variant_section: true,
        variant_selection_txt: "Select",
        sold_out_txt: "Sold Out",
        show_product_vendor: false,
        show_price_in_dropdown: true,
      },
      discount: {
        selected_discount: "automatic",
        selected_discount_type: "percentage",
        discount_code: "",
        discount_value: "0.00",
        only_apply_products: "0",
        discount_prefix: "Special deal",
        selected_price_display_option: "",
        compare_price_color: "#000",
        selling_price_color: "#000",
      },
      timer: {
        add_timer: false,
        timer_txt: "Offer expires in:",
        selected_display_timer: "",
        days: 0,
        hours: 0,
        minutes: 5,
        seconds: 0,
        timer_style: 1,
        timer_bg_color: "#e1f3f3",
        timer_color: "#000",
        timer_text_color: "#6bc0c0",
        timer_border_color: "#6bc0c0",
        selected_position: "above_title",
        selected_text_position: "left_timer",
        days_txt: "",
        hours_txt: "",
        minutes_txt: "",
        seconds_txt: "",
        selected_timer_runs_out: "",
        timer_expired_msg: "Offer expired",
        preview_offer: true,
      },
      buttons: {
        show_quick_view: true,
        btn_text: "Quick View",
        btn_bg_color: "#197bbd",
        btn_color: "#fff",
        show_view_all_btn: true,
        collection_redirect_url: "/all",
        view_btn_text: "View All",
        view_btn_bg_color: "#197bbd",
        view_btn_color: "#fff",
        accept_btn: "Buy now",
        accept_btn_bg_color: "#197bbd",
        accept_btn_color: "#fff",
      },
    },
    status: 1,
    iconName: `<i className=\"ri-price-tag-3-fill\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 14,
    section_name: "Product upsell",
    settings: {
      title: {
        offer_name: "Offer name",
        widget_title: "",
        selected_disp_widget: "above_widget",
        widget_title_bg_color: "transparent",
      },
      product_options: {
        products_display: "Most expensive product purchase",
        exclusion_tag: false,
        exclusion_tags: [],
        selected_layout: "large",
        title: "",
        selected_product_title: "above_image",
        product_des: "",
        arrow_color: "#000",
        display_qty_picker: true,
        qty_picker_txt: "Quantity",
        sold_out_txt: "Sold Out",
        show_product_vendor: false,
        display_description: false,
      },
      discount: {
        selected_discount: "automatic",
        selected_discount_type: "percentage",
        discount_value: "0.00",
        only_apply_products: "0",
        discount_prefix: "Thanks",
        display_compare_price: true,
        compare_price_fs_price: 14,
        compare_price_color: "#000",
        display_product_price: false,
        product_price_fs_price: 14,
        product_price_color: "#000",
        discount_price: true,
        discount_fs_size: 14,
        discount_color: "#000",
        discount_code: "",
      },
      timer: {
        add_timer: false,
        timer_txt: "Offer expires in:",
        selected_display_timer: "",
        days: 0,
        hours: 0,
        minutes: 0,
        seconds: 0,
        timer_style: 1,
        timer_bg_color: "#e1f3f3",
        timer_color: "#000",
        timer_text_color: "#6bc0c0",
        timer_border_color: "#6bc0c0",
        selected_position: "above_widget",
        selected_text_position: "left_timer",
        days_txt: "",
        hours_txt: "",
        minutes_txt: "",
        seconds_txt: "",
        selected_timer_runs_out: "",
        timer_expired_msg:
          '<p style="text-align:center;"><span style="font-size: 24px;">Offer expired</span></p>\n',
        preview_offer: true,
      },
      buttons: {
        btn_text: "Buy now",
        btn_bg_color: "#197bbd",
        btn_color: "#fff",
      },
    },
    status: 1,
    iconName: `<i className=\"ri-price-tag-2-fill\" aria-hidden=\"true\"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 15,
    section_name: "Reorder",
    title:
      '<p><span style="font-size: 30px;"><strong>Title</strong></span></p>\n<p></p>\n<p><strong>Reorder now and get X OFF!</strong></p>\n',
    loader_text:
      '<p style="text-align:left;">Please wait for a few seconds while we recreate your order</p>\n',
    selected_discount_type: "percentage",
    discount_value: 0,
    discount_name: "Reorder Deal",
    free_ship: false,
    free_ship_name: "Free",
    btn_text: "Re-order button",
    btn_alignment: "left",
    bg_color: "#197bbd",
    color: "#fff",
    status: 1,
    iconName: `<i className="fa fa-download" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 16,
    section_name: "Social follow buttons",
    content: [],
    status: 1,
    iconName: `<i className="fa fa-thumbs-up" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 17,
    section_name: "Social media links",
    title:
      '<p><span style="font-size: 16px;"><strong>Visit us on social media:</strong></span></p>\n',
    selected_icon_style: "logo",
    facebook_link: "#",
    twitter_link: "#",
    pinterest_link: "#",
    instagram_link: "#",
    linkedin_link: "#",
    tumblr_link: "#",
    google_link: "#",
    youtube_link: "#",
    status: 1,
    iconName: `<i className="fa fa-thumbs-up" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 18,
    section_name: "Social sharing",
    title:
      '<p style="text-align:center;"><span style="font-size: 14px;">Share your order on social media</span></p>\n',
    discount_code: "",
    selected_icon_style: "logo",
    btn_alignment: "center",
    share_facebook: true,
    share_twitter: true,
    share_pinterest: true,
    share_linkedin: true,
    share_google: false,
    status: 1,
    iconName: `<i className="fa fa-thumbs-up" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
  {
    section_id: 19,
    section_name: "Video",
    title:
      '<p><span style="font-size: 18px;"><strong>Video</strong></span></p>\n',
    video_type: "youtube",
    video_id: "_9VUPq3SxOc",
    auto_play: false,
    status: 1,
    iconName: `<i className="ri-video-line" aria-hidden="true"></i>`,
    is_fa_icon: true,
    is_disabled: false,
  },
];
