import DBOperation from "../services/database_operation.js";
import SchemaModel from "../services/schema_model.js";
import { v4 as uuidv4 } from "uuid";

const schema = {
  funnel_offer_id: {
    type: String,
    default: uuidv4,
  },
  offer_name: String,
  direction: String,
  location_no: String,
  main_image_gr: String,
  parent_id: String,
  product_id: Number,
  product_title: String,
  shop: String,
  store_client_id: Number,
  funnel_id: {
    type: String,
    ref: "funnels",
  },
  offer_id: {
    type: String,
    ref: "offers",
  },
  acc_btn_txt: String,
  acc_btn_type: String,
  alter_product_id: String,
  alter_option: String,
  arrow_clr: String,
  configure_tax_inclusivity: { type: Boolean, default: false },
  btn_bg_clr: String,
  btn_clr: String,
  checkout_input_bg_clr: String,
  checkout_accent_clr: String,
  checkout_body_bg_clr: String,
  checkout_err_clr: String,
  checkout_input_border_clr: String,
  checkout_txt_clr: String,
  compare_at_price_font_size: String,
  days: String,
  days_text: String,
  decline_btn_txt_position: String,
  decline_btn_type: String,
  decline_btn_txt: String,
  default_variant_txt: String,
  default_variants: String,
  discount_over_order_value: String,
  discount_txt: String,
  discount_type: String,
  discount_value: Number,
  discount_font_size: String,
  display_timer: String,
  exclude_product_by_tag: String,
  expiry_settings: String,
  extra_fields: String,
  fallback_ship_rate: String,
  hours: String,
  hours_txt: String,
  image: String,
  is_allow_discount: String,
  is_editor: String,
  is_shipping: String,
  is_show_compare_price: String,
  is_show_discount_price: String,
  is_show_exclusion_tags: String,
  is_show_product_price: String,
  is_show_qty: String,
  is_show_variant: String,
  is_timer_added: String,
  main_img: String,
  main_product_img: String,
  minute: String,
  minute_txt: String,
  price_clr_priority: String,
  price_font_size: String,
  product_des: String,
  product_id: String,
  product_title: String,
  product_title_place: String,
  product_type: String,
  qty_txt: String,
  save_btn_status: String,
  secondary_options: String,
  seconds: String,
  seconds_txt: String,
  shipping_rate: String,
  shipping_txt: String,
  shop: String,
  slide_to_display: String,
  slider_style: String,
  soldout_txt: String,
  sub_total_txt: String,
  tax_line: String,
  tax_shipping: { type: Boolean, default: false },
  taxes_inclueded: { type: Boolean, default: false },
  taxes_txt: String,
  timer_bg_clr: String,
  timer_clr: String,
  timer_exp_msg: String,
  timer_offer_txt: String,
  timer_position: String,
  timer_txt_clr: String,
  timer_txt_position: String,
  title: String,
  total_txt: String,
  widget_title: String,
  widget_title_place: String,
  thankyou_page: {
    type: Boolean,
    default: false,
  },
  temp_id: String,
  type: String,
};

const modelName = "funnel_offer";

export let FunnelOfferModel = DBOperation.createModel(modelName, schema);

let funnelOfferModel = new SchemaModel(FunnelOfferModel);
export default funnelOfferModel;
