import DBOperation from "../services/database_operation.js";
import SchemaModel from "../services/schema_model.js";
import { v4 as uuidv4 } from "uuid";

/**
 * STATUS
 * 0 - Inactive
 * 1 - Active
 */

const schema = {
  row_section_id: {
    type: String,
    default: uuidv4,
  },
  template_id: String,
  section_id: String,
  section_name: String,
  title: String,
  display_donation_btn: String,
  btn_text: String,
  bg_color: String,
  color: String,
  status: {
    type: Number,
    enum: [0, 1],
    default: 1,
  },
  iconName: String,
  is_fa_icon: {
    type: Boolean,
    default: false,
  },
  is_disabled: {
    type: Boolean,
    default: false,
  },
  date_format: [Object],
  placeholder_text: String,
  thank_you_msg_txt: String,
  thank_you_msg_txt_color: String,
  error_msg: String,
  error_msg_color: String,
  selected_date_format: String,
  redirect_url: String,
  selected_layout: String,
  layout: [Object],
  heading: String,
  head_color: String,
  head_fs_size: String,
  head_style: [String],
  head_selected_text_transform: String,
  coll_title_color: String,
  coll_fs_size: String,
  coll_style: [String],
  coll_selected_text_transform: String,
  coll_per_row: Number,
  content: [Object],
  custom_html: String,
  btn_bg_color: String,
  btn_color: String,
  discount_code: String,
  discount_bg_color: String,
  discount_color: String,
  term_condition_txt: String,
  img: String,
  selected_img_align: String,
  selected_img_layout: String,
  links: [Object],
  next_btn_text: String,
  next_btn_bg_color: String,
  next_btn_color: String,
  prev_btn_text: String,
  prev_btn_bg_color: String,
  prev_btn_color: String,
  thank_you_msg: String,
  place_holder_answer: String,
  place_holder_dropdown: String,
  questions: [Object],
  select_survey: String,
  settings: {
    _id: false,
    title: {
      offer_name: String,
      widget_title: String,
      selected_disp_widget: String,
      widget_title_bg_color: String,
    },
    product_options: {
      products_display: String,
      exclusion_tag: {
        type: Boolean,
        default: false,
      },
      exclusion_tags: [String],
      hide_product: {
        type: Boolean,
        default: false,
      },
      loader_text: String,
      title: String,
      products_per_row: Number,
      no_of_product: Number,
      arrow_color: String,
      display_qty_picker: {
        type: Boolean,
        default: true,
      },
      qty_picker_txt: String,
      enable_variant_section: {
        type: Boolean,
        default: true,
      },
      variant_selection_txt: String,
      sold_out_txt: String,
      show_product_vendor: {
        type: Boolean,
        default: false,
      },
      show_price_in_dropdown: {
        type: Boolean,
        default: true,
      },
      selected_layout: String,
      selected_product_title: String,
      product_des: String,
      display_description: {
        type: Boolean,
        default: false,
      },
    },
    discount: {
      selected_discount: String,
      selected_discount_type: String,
      discount_value: String,
      only_apply_products: String,
      discount_prefix: String,
      selected_price_display_option: String,
      compare_price_color: String,
      selling_price_color: String,
      discount_code: String,
      display_compare_price: {
        type: Boolean,
        default: true,
      },
      compare_price_fs_price: Number,
      display_product_price: {
        type: Boolean,
        default: false,
      },
      product_price_fs_price: Number,
      product_price_color: String,
      discount_price: {
        type: Boolean,
        default: true,
      },
      discount_fs_size: Number,
      discount_color: String,
    },
    timer: {
      add_timer: {
        type: Boolean,
        default: false,
      },
      timer_txt: String,
      selected_display_timer: String,
      days: Number,
      hours: Number,
      minutes: Number,
      seconds: Number,
      timer_style: Number,
      timer_bg_color: String,
      timer_color: String,
      timer_text_color: String,
      timer_border_color: String,
      selected_position: String,
      selected_text_position: String,
      days_txt: String,
      hours_txt: String,
      minutes_txt: String,
      seconds_txt: String,
      selected_timer_runs_out: String,
      timer_expired_msg: String,
      preview_offer: {
        type: Boolean,
        default: false,
      },
    },
    buttons: {
      show_quick_view: {
        type: Boolean,
        default: true,
      },
      btn_text: String,
      btn_bg_color: String,
      btn_color: String,
      show_view_all_btn: {
        type: Boolean,
        default: true,
      },
      collection_redirect_url: String,
      view_btn_text: String,
      view_btn_bg_color: String,
      view_btn_color: String,
      accept_btn: String,
      accept_btn_bg_color: String,
      accept_btn_color: String,
    },
  },
  loader_text: String,
  selected_discount_type: String,
  discount_value: String,
  discount_name: String,
  free_ship: {
    type: Boolean,
    default: false,
  },
  free_ship_name: String,
  btn_alignment: String,
  selected_icon_style: String,
  facebook_link: String,
  twitter_link: String,
  pinterest_link: String,
  instagram_link: String,
  linkedin_link: String,
  tumblr_link: String,
  google_link: String,
  youtube_link: String,
  share_facebook: {
    type: Boolean,
    default: true,
  },
  share_twitter: {
    type: Boolean,
    default: true,
  },
  share_pinterest: {
    type: Boolean,
    default: true,
  },
  share_linkedin: {
    type: Boolean,
    default: true,
  },
  share_google: {
    type: Boolean,
    default: false,
  },
  video_type: String,
  video_id: String,
  auto_play: {
    type: Boolean,
    default: false,
  },
  area: String,
  is_order_track: {
    type: Boolean,
    default: false,
  },
  is_product_comment: {
    type: Boolean,
    default: false,
  },
  is_magic: {
    type: Boolean,
    default: false,
  },
};

const modelName = "section";

export let SectionModel = DBOperation.createModel(modelName, schema);

let sectionModel = new SchemaModel(SectionModel);
export default sectionModel;
